return {
	-- {
	-- 	"nvim-telescope/telescope.nvim",
	-- 	dependencies = { "nvim-treesitter/nvim-treesitter" },
	-- 	event = "VimEnter",
	-- 	config = function()
	-- 		require("telescope").setup({
	-- 			defaults = {
	-- 				prompt_prefix = "   ",
	-- 				selection_caret = " ",
	-- 				entry_prefix = " ",
	-- 				sorting_strategy = "ascending",
	-- 				layout_config = {
	-- 					horizontal = {
	-- 						prompt_position = "top",
	-- 						preview_width = 0.55,
	-- 					},
	-- 					width = 0.87,
	-- 					height = 0.80,
	-- 				},
	-- 				mappings = {
	-- 					n = { ["q"] = require("telescope.actions").close },
	-- 				},
	-- 				file_ignore_patterns = { "^.git/", "^node_modules/" },
	-- 			},
	-- 			pickers = {
	-- 				find_files = {
	-- 					follow = true,
	-- 					hidden = true,
	-- 				},
	-- 				grep_string = {
	-- 					additional_args = { "--hidden" },
	-- 				},
	-- 				live_grep = {
	-- 					additional_args = { "--hidden" },
	-- 				},
	-- 			},
	--
	-- 			extensions_list = { "themes", "terms" },
	-- 			extensions = {},
	-- 		})
	-- 	end,
	-- },
}
